### PR TITLE
🐛 184 - Fix live banner

### LINKED ISSUE #184: 🐛 UG Live Banner styling broken
```[tasklist]
### Tasks
- [x] Make text fit on banner
- [x] Make banner full width
- [x] Add minutes to countdown
- [x] Make banner show on mobile phones (portait layout)
- [x] Set up state for isLive for when minutes tick over to live
- [x] Filter to only user group events
```

Image
**FIgure: New website 😒**

Image
**FIgure: Old website**

This was working, but a styling change must have effected it.
See the done video https://github.com/SSWConsulting/SSW.Website-v3/pull/55#issue-1550224872

### PR DESCRIPTION
**Pull request by Harry-Ross**
Closes #184 

> Make text fit on banner
> Make banner full width

image

> Add minutes to countdown
> Set up state for isLive for when minutes tick over to live

Minutes/hours now count down, updating every minute:

image
image
**Figure: Switching from 1 to 0 minutes.**

> Make banner show on mobile phones (portait layout)

image
**Figure: Responsive layout on iPhone XR**

> Filter to only user group events

This also reduces the request size from the `https://www.ssw.com.au/ssw/SharePointEventsService.aspx` endpoint significantly, with a reduction from 141kb to 8kb by adding a filter to the request.

### CODE REVIEW

File: components/liveStreamBanner.tsx [hunk 1]
```diff
@@ -45,45 +52,62 @@ export const LiveStreamBanner = () => {
...
           )}
         >
-          <h1 className="text-xl font-light text-gray-300">{event.Title}</h1>
-          <p className=" text-xs text-white">
+          <h1 className="m-0 py-0 text-xl font-light text-gray-300">{event.Title}</h1>
+          <p className="py-0 text-xs text-white">
             <span className="text-sswRed">
               {isLive ? liveText : countdownText}
             </span>
             {!isLive && scheduledTimeText(startDateTime)} #NetUG
```
Comment (wicksipedia) [inline components/liveStreamBanner.tsx:106]: Can this be sourced from somewhere instead of being hard coded?
I know we sometimes livestream the #NCCG and it would be good to use their hashtag when appropriate

File: helpers/countdownTextFormat.ts [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+      countdownText += " and ";
+    }
+  
+    if (minutes > 1) {
+      countdownText += `${minutes} minutes`;
+    } else if (minutes === 1 || minutes == 0) {
+      countdownText += "1 minute";
+    } 
+  
+    return `Airing in ${countdownText}. `;
```
Comment (wicksipedia) [inline helpers/countdownTextFormat.ts:23]: Can you refactor the "Airing in" text out so that its more generic

File: components/liveStreamBanner.tsx (hunk 1 above)
Comment (Harry-Ross) [reply components/liveStreamBanner.tsx:107]: As per our conversation, I raised issue #236

**Review by wicksipedia — APPROVED** [review]

**Review by wicksipedia — APPROVED** [review]
